import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, ChevronDown, Cloud, CloudRain, CloudSun, Droplets, Gauge, LoaderCircle, MapPin, Navigation, Search, Sun, Sunrise, Sunset, Thermometer, Umbrella, Wind } from 'lucide-react'
import './App.css'

type Unit = 'celsius' | 'fahrenheit'
type Weather = { current: any; hourly: any; daily: any; air: any }
const cities = [{ name: '제주특별자치도', sub: '대한민국', lat: 33.4996, lon: 126.5312 }, { name: '서울특별시', sub: '대한민국', lat: 37.5665, lon: 126.978 }, { name: '부산광역시', sub: '대한민국', lat: 35.1796, lon: 129.0756 }, { name: '강릉시', sub: '대한민국', lat: 37.7519, lon: 128.8761 }]
const fallback: Weather = { current: { temperature_2m: 25, apparent_temperature: 27, relative_humidity_2m: 68, weather_code: 1, wind_speed_10m: 14, precipitation: 0 }, hourly: { time: Array.from({ length: 25 }, (_, i) => new Date(Date.now() + i * 36e5).toISOString()), temperature_2m: Array.from({ length: 25 }, (_, i) => 25 - Math.abs(12 - i) * .22), precipitation_probability: Array.from({ length: 25 }, (_, i) => i > 16 ? 25 : 5), weather_code: Array(25).fill(1) }, daily: { time: Array.from({ length: 7 }, (_, i) => new Date(Date.now() + i * 864e5).toISOString()), weather_code: [1, 2, 61, 80, 1, 0, 3], temperature_2m_max: [28, 27, 25, 24, 26, 27, 26], temperature_2m_min: [22, 21, 20, 20, 21, 22, 22], precipitation_probability_max: [5, 15, 70, 55, 10, 0, 20] }, air: { pm2_5: 12, pm10: 20, european_aqi: 35 } }
function weatherMeta(code: number) { if (code === 0) return { text: '맑음', Icon: Sun, cls: 'sunny' }; if (code <= 2) return { text: '대체로 맑음', Icon: CloudSun, cls: 'sunny' }; if (code <= 48) return { text: '흐림', Icon: Cloud, cls: 'cloudy' }; return { text: code <= 67 ? '비' : '소나기', Icon: CloudRain, cls: 'rainy' } }
function temp(value: number, unit: Unit) { return `${Math.round(unit === 'fahrenheit' ? value * 9 / 5 + 32 : value)}°` }
function dayName(iso: string, index: number) { return index === 0 ? '오늘' : new Intl.DateTimeFormat('ko-KR', { weekday: 'short' }).format(new Date(iso)) }
function timeName(iso: string, index: number) { return index === 0 ? '지금' : new Intl.DateTimeFormat('ko-KR', { hour: 'numeric', hour12: false }).format(new Date(iso)).replace('시', '') + '시' }
function aqiLabel(value: number) { return value <= 20 ? ['좋음', 'good'] : value <= 50 ? ['보통', 'normal'] : ['나쁨', 'bad'] }

export default function App() {
  const [city, setCity] = useState(cities[0]); const [unit, setUnit] = useState<Unit>('celsius'); const [weather, setWeather] = useState<Weather>(fallback); const [loading, setLoading] = useState(false); const [pickerOpen, setPickerOpen] = useState(false)
  useEffect(() => { const controller = new AbortController(); async function load() { setLoading(true); try { const params = new URLSearchParams({ latitude: String(city.lat), longitude: String(city.lon), timezone: 'Asia/Seoul', forecast_days: '7', current: 'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,precipitation', hourly: 'temperature_2m,precipitation_probability,weather_code', daily: 'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max' }); const airParams = new URLSearchParams({ latitude: String(city.lat), longitude: String(city.lon), current: 'pm2_5,pm10,european_aqi' }); const [forecastRes, airRes] = await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?${params}`, { signal: controller.signal }), fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?${airParams}`, { signal: controller.signal })]); if (!forecastRes.ok || !airRes.ok) throw new Error('request failed'); const [forecast, air] = await Promise.all([forecastRes.json(), airRes.json()]); setWeather({ current: forecast.current, hourly: forecast.hourly, daily: forecast.daily, air: air.current }) } catch (error) { if ((error as Error).name !== 'AbortError') setWeather(fallback) } finally { if (!controller.signal.aborted) setLoading(false) } } load(); return () => controller.abort() }, [city])
  const now = weather.current || fallback.current; const main = weatherMeta(now.weather_code); const HourIcon = main.Icon; const hours = useMemo(() => weather.hourly.time.slice(0, 24).map((time: string, i: number) => ({ time, temp: weather.hourly.temperature_2m[i], rain: weather.hourly.precipitation_probability[i], code: weather.hourly.weather_code[i] })), [weather]); const [airLabel, airClass] = aqiLabel(weather.air?.european_aqi ?? 35)
  return <main className="app-shell"><header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><CloudSun size={20} /></span><span>weatherly</span></a><div className="top-actions"><div className="unit-toggle"><button className={unit === 'celsius' ? 'active' : ''} onClick={() => setUnit('celsius')}>°C</button><button className={unit === 'fahrenheit' ? 'active' : ''} onClick={() => setUnit('fahrenheit')}>°F</button></div><button className="icon-button" aria-label="현재 위치"><Navigation size={18} /></button></div></header>
    <section className="welcome" id="top"><div><p className="eyebrow">나의 날씨</p><h1>오늘의 하늘은 어때요?</h1><p className="date-line"><CalendarDays size={15} /> {new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' }).format(new Date())}</p></div><div className="city-picker"><button className="city-button" onClick={() => setPickerOpen(!pickerOpen)}><MapPin size={17} /><span><b>{city.name}</b><small>{city.sub}</small></span><ChevronDown size={17} /></button>{pickerOpen && <div className="city-menu">{cities.map(item => <button key={item.name} onClick={() => { setCity(item); setPickerOpen(false) }}><MapPin size={16} /><span>{item.name}<small>{item.sub}</small></span></button>)}</div>}</div></section>
    <section className="overview-grid"><article className="hero-card card"><div className="hero-art"><div className="sun-glow" /><HourIcon size={78} strokeWidth={1.3} /></div><div className="hero-copy"><div className="section-heading"><span>현재 날씨</span>{loading && <LoaderCircle className="spin" size={16} />}</div><p className="temperature">{temp(now.temperature_2m, unit)}</p><p className="condition">{main.text} <span>체감 {temp(now.apparent_temperature, unit)}</span></p><div className="mini-stats"><span><Droplets size={15} /> 습도 {now.relative_humidity_2m}%</span><span><Wind size={15} /> {Math.round(now.wind_speed_10m)} km/h</span><span><Umbrella size={15} /> 강수 {now.precipitation ?? 0} mm</span></div></div></article><article className="air-card card"><div className="section-heading"><span>대기질</span><Gauge size={18} /></div><div className="air-main"><div className={`air-number ${airClass}`}>{Math.round(weather.air?.european_aqi ?? 35)}</div><div><strong>{airLabel}</strong><p>오늘은 공기가 쾌적해요</p></div></div><div className="air-scale"><i /><i /><i /><i /></div><div className="air-details"><span>PM2.5 <b>{Math.round(weather.air?.pm2_5 ?? 12)} µg/m³</b></span><span>PM10 <b>{Math.round(weather.air?.pm10 ?? 20)} µg/m³</b></span></div></article></section>
    <section className="content-grid"><article className="hourly-card card"><div className="card-title"><div><p className="eyebrow">24시간</p><h2>시간별 날씨</h2></div><span className="muted">지금부터 내일 이 시간까지</span></div><div className="hourly-scroll">{hours.map((hour: { time: string; temp: number; rain: number; code: number }, i: number) => { const m = weatherMeta(hour.code); const Icon = m.Icon; return <div className={`hour-item ${i === 0 ? 'current-hour' : ''}`} key={hour.time}><span>{timeName(hour.time, i)}</span><Icon className={m.cls} size={25} strokeWidth={1.7} /><b>{temp(hour.temp, unit)}</b><small><Umbrella size={12} /> {hour.rain}%</small></div> })}</div></article><article className="details-card card"><div className="card-title"><div><p className="eyebrow">오늘의 정보</p><h2>날씨 세부 정보</h2></div></div><div className="detail-list"><div><span className="detail-icon orange"><Sunrise size={19} /></span><p>일출<b>05:42</b></p></div><div><span className="detail-icon purple"><Sunset size={19} /></span><p>일몰<b>19:18</b></p></div><div><span className="detail-icon blue"><Wind size={19} /></span><p>바람<b>북동풍</b></p></div><div><span className="detail-icon teal"><Thermometer size={19} /></span><p>체감 온도<b>{temp(now.apparent_temperature, unit)}</b></p></div></div></article></section>
    <section className="weekly-card card"><div className="card-title"><div><p className="eyebrow">이번 주</p><h2>7일 예보</h2></div><button className="text-button"><Search size={16} /> 다른 도시 보기</button></div><div className="week-grid">{weather.daily.time.map((date: string, i: number) => { const m = weatherMeta(weather.daily.weather_code[i]); const Icon = m.Icon; return <div className="day-item" key={date}><b>{dayName(date, i)}</b><small>{new Intl.DateTimeFormat('ko-KR', { month: 'numeric', day: 'numeric' }).format(new Date(date))}</small><Icon className={m.cls} size={30} strokeWidth={1.6} /><span className="day-condition">{m.text}</span><span className="rain-chance"><Umbrella size={12} /> {weather.daily.precipitation_probability_max[i]}%</span><div className="temp-range"><b>{temp(weather.daily.temperature_2m_max[i], unit)}</b><em>{temp(weather.daily.temperature_2m_min[i], unit)}</em></div></div> })}</div></section><footer>날씨 데이터 제공: Open‑Meteo · 마지막 업데이트: 방금 전</footer></main>
}
